### ISSUE TITLE
Question about reproducing the experiments of Zurich datasets and Eliceiri datasets

### ISSUE THREAD

**Issue by lajipeng** [Noodles-321/Registration#2] opened 2021-10-09 16:58 UTC
Hello~I'm very interested in your research. I tried to reproducing the experiments of Zurich datasets and Eliceiri datasets with the pre-trained model (https://github.com/MIDA-group/CoMIR/releases/tag/1.0). But it seemed that the results were not consistent with this paper (b2a Zurich sift: 92.7% aAMD:35% Eliceiri sift: 10% ). I guessed that the two paper may used two different weights or due to the machine difference. Could you provide the weights used in this model so that we can follow your pioneering job for comparison?

**Comment by ludles** [comment] 2021-10-11 08:00
Hello, Alan!

Thanks for your interest in our work!

But firstly, you should not expect to reproduce our results using model weights trained for another project. 🙂 There are at least some differences in training settings.

Our results are reproducible if following the steps described in our paper. All code used is included in this repository. Taking CoMIR for example, due to our experience, training from scratch on a single NVIDIA RTX 2080Ti should not take more than 48 hours.

Anyhow, if you are particularly interested in our trained model weights, I hope our [trained weights in this link](https://uppsalauniversitet-my.sharepoint.com/:u:/g/personal/jiahao_lu_2199_student_uu_se1/EYsJK_L2731GmSyPVHC1YUgBjVXioTsKrxG998Dv-8-vkg?e=OhvJYf) is helpful. 

I am closing this issue. But please feel free to re-open it if you have further questions.

**Closed as completed by ludles** 2021-10-11 08:00 UTC

**Comment by lajipeng** [comment] 2021-10-11 13:34
I sincerely appreciate your help! It helps me a lot. I mistakenly assumed that the test and training sets for both papers were the same. You have done 3-fold cross-validation in Zurich and Balvan datasets. But I have a further question. What's the training datasets of Eliceiri? The COMIR took 40 image pairs as training datasets. How about this paper?

**Comment by ludles** [comment] 2021-10-11 14:40
To directly answer your question, the training set for the Histological data is clearly defined in [Multimodal Biomedical Dataset for Evaluating Registration Methods (Full-size TMA Cores)](https://zenodo.org/record/4550300), where no 3-fold cross-validation is used. (It is cited in Sec. 4.3 of our paper, both as a reference and footnote, is also cited in the README of our dataset page and exists in the `Related identifiers` area of our released dataset.) And I would recommend you to read our paper for experiment details, and perhaps also take a look at our [`Datasets/`](https://github.com/MIDA-group/MultiRegEval/tree/master/Datasets) folder for the code to handle the raw data.

I hope this answers your question. 🙂
